### ISSUE TITLE
IP 数据出错

### ISSUE THREAD

**Issue by ZeroClover** [tmplink/IPDB#1]
在 commit 6bcd138 内，CN 的 IPv4 和 IPv6 都被删除了 90% 以上的条目。

这是否可能是更新 IP 库的自动程序的问题？

**Comment by 2CW** [comment]
刚刚已经加回来了

**Comment by tmplink** [comment]
> 在 commit [6bcd138](https://github.com/tmplink/IPDB/commit/6bcd138e259369be693262605cdffed25c00afe6) 内，CN 的 IPv4 和 IPv6 都被删除了 90% 以上的条目。
> 
> 这是否可能是更新 IP 库的自动程序的问题？

不会是程序问题，程序已经运行多年了。
此情况在之前的以往更新中偶尔会出现，是因为数据源也在更新，就会碰到这种问题。

通常在第二天的更新中就会修复这个问题。

**Comment by grayguest** [comment]
应该做个判断吧，这种90%大批量的删除肯定是有问题的。
