### ISSUE TITLE
Feature request: offering .mmdb format.

### ISSUE THREAD

**Issue by vndi** [tmplink/IPDB#4]
Hi there,
Your project has been a great help, but as .txt don't have wide support in recent apps like Clash or Surge, I wonder have you ever consider offer a .mmdb format so more people can use it in their daily drive apps?

**Comment by tmplink** [comment]
It doesn't seem to do it.
It is not compatible because the format is different.
IPDB is a national level IP database, while mmdb is based on maxmind and requires more details.
